#!/bin/sh

# fzf
# https://github.com/junegunn/fzf

# Dependencies:
# – bat (https://github.com/sharkdp/bat)

# Arguments
pattern=$1

:ls |
grep -F "$pattern" |
fzf --preview-window=down:60% --preview 'bat --style=numbers --color=always --line-range :500 {}' --prompt='(b)>' |
:buffer
