#!/bin/sh

# Rofi
# https://github.com/davatorium/rofi

# Dependencies:
# – fd (https://github.com/sharkdp/fd)

. "$KAKOUNE_PRELUDE"

:edit "$(kak_escape "$(
  fd --type file . "$@" |
  rofi -dmenu -i -p 'Open files'
)")"
