#!/bin/sh

# Faces
none='\033[0m'
yellow='\033[33m'
magenta='\033[35m'

if [ -n "$KAKOUNE_SESSION" ] && [ -n "$KAKOUNE_CLIENT" ]; then
  printf "${magenta}${KAKOUNE_CLIENT}${none} at ${yellow}${KAKOUNE_SESSION}${none}"

elif [ -n "$KAKOUNE_SESSION" ]; then
  printf "(${yellow}${KAKOUNE_SESSION}${none})"

fi
