#!/bin/sh

. "$KAKOUNE_PRELUDE"

# Skip options
[ "$1" = '--' ] && shift

# Open files
commands=$(
  while [ "$1" ]; do
    case "$1" in
      ('+'*':'*)
        line=${1#+}; line=${line%:*}
        column=${1#*:}
        file=$(realpath "$2")
        shift 2
        kak_escape edit "$file" "$line" "$column"
        ;;
      ('+'*)
        line=${1#+}
        file=$(realpath "$2")
        shift 2
        kak_escape edit "$file" "$line"
        ;;
      (*)
        file=$(realpath "$1")
        shift 1
        kak_escape edit "$file"
        ;;
    esac
  done
)

:send "$commands"

# Focus back the client
:send focus
