#!/bin/sh

BUFNAME=${BUFNAME:-*fifo*}
# Edit fifo buffer in a client
FIFODIR=$(mktemp -d -t "connect.kak")
mkfifo "$FIFODIR/buffer.fifo"
trap "rm -rf '$FIFODIR'" EXIT
:send edit! -fifo "$FIFODIR/buffer.fifo" "$BUFNAME"

# Send to fifo buffer the output of the given command,
# or read from stdin if available.
#
# Example:
#
# :fifo make
#
if test $# -gt 0; then
  "$@" > "$FIFODIR/buffer.fifo" 2>&1 &
elif test ! -t 0; then
  cat > "$FIFODIR/buffer.fifo"
fi

# Focus back the client
:send focus
