#!/bin/sh

# Edit fifo buffer in a client
mkfifo buffer.fifo
trap 'rm buffer.fifo' EXIT
:send edit! -fifo "$PWD/buffer.fifo" '*fifo*'

# Send to fifo buffer the output of the given command,
# or read from stdin if available.
#
# Example:
#
# :fifo make
#
if test $# -gt 0; then
  "$@" > buffer.fifo 2>&1 &
elif test ! -t 0; then
  cat > buffer.fifo
fi

# Focus back the client
:send focus
