#!/bin/sh

# Wofi
# https://hg.sr.ht/~scoopta/wofi

# Dependencies:
# – fd (https://github.com/sharkdp/fd)

. "$KAKOUNE_PRELUDE"

:edit "$(kak_escape "$(
  fd --type file . "$@" |
  wofi --dmenu --prompt 'Open files'
)")"
