#!/bin/sh

# fzy
# https://github.com/jhawthorn/fzy

# Dependencies:
# – ripgrep (https://github.com/BurntSushi/ripgrep)

rg --line-number --with-filename '.+' "$@" |
fzy --prompt='(g)>' |

while read line; do
  # Output format: <file>:<line>:<text>
  file=${line%%:*}
  line_number=${line#*:}; line_number=${line_number%%:*}

  :edit "$file" "+$line_number"
done
