#!/bin/sh

# Attach a command ran from Kakoune with :connect-detach.

if test -e "$KAKOUNE_CONNECT_SCRIPT"; then
  mv "$KAKOUNE_CONNECT_SCRIPT" "$KAKOUNE_CONNECT_SCRIPT~"
  sh "$KAKOUNE_CONNECT_SCRIPT~"
  # Note:
  # This script is deleted by :connect-detach when reattaching to the session.
  # If the script still exists, sh <connect-script> did not reattach.
  # Mitigate the need to manually reattach.
  if test -e "$KAKOUNE_CONNECT_SCRIPT~"; then
    rm -f "$KAKOUNE_CONNECT_SCRIPT~"
    edit
  fi
fi
