#!/bin/sh

# Prelude
. "$KAKOUNE_CONNECT_PATH/functions/prelude.sh"

main() {
  if test $# -eq 0; then
    list
  else
    edit "$@"
  fi
}

list() {
  kak_quoted_buflist=$(get '%val{buflist}')
  eval "set -- $kak_quoted_buflist"
  printf '%s\n' "$@"
}

edit() {
  commands=''
  for buffer do
    kak_quoted_buffer=$(kak_escape "$buffer")
    commands="buffer $kak_quoted_buffer; $commands"
  done
  send "$commands"
}

main "$@"
