#!/bin/sh

. "$KAKOUNE_PRELUDE"

main() {
  if test $# -eq 0; then
    list
  else
    edit "$@"
    # Try to attach a connect terminal command
    attach
  fi
}

list() {
  kak_quoted_buflist=$(get '%val{buflist}')
  eval "set -- $kak_quoted_buflist"
  printf '%s\n' "$@"
}

edit() {
  commands=''
  for buffer do
    kak_quoted_buffer=$(kak_escape "$buffer")
    commands="buffer $kak_quoted_buffer; $commands"
  done
  # Attach to terminal.
  # Ensure there is a terminal.
  if test -t 1 -a "$KAKOUNE_CONNECT_ATTACH" = true; then
    kak -c "$KAKOUNE_SESSION" -e "$commands"
  else
    send "$commands"
  fi
}

main "$@"
