#!/bin/sh

# Environment variables
# Set a default client value
KAKOUNE_CLIENT=${KAKOUNE_CLIENT:-client0}

state=$(mktemp -d)
trap 'rm -Rf "$state"' EXIT
mkfifo "$state/fifo"

send echo -to-file "$state/fifo" "$@"
cat "$state/fifo"
