#!/bin/sh

# Environment variables
OS=$(uname -s)

# Platform-specific settings
OPENER=$(
  PATH=$ORIGINAL_PATH
  case "$OS" in
    Linux|FreeBSD|OpenBSD) opener=xdg-open ;;
    Darwin) opener=open ;;
  esac
  which "$opener"
)

main() {
  for file do
    open "$file" < /dev/null > /dev/null 2>&1 &
  done
}

open() {
  file=$1
  mime=$(mime "$file")
  case "$mime" in
    text/*) opener=edit ;;
    *) opener=$OPENER ;;
  esac
  command "$opener" "$file"
}

mime() {
  mime=$(file -b -i -L -- "$1")
  mime=${mime%;*}
  printf '%s' "$mime"
}

main "$@"
