#!/bin/sh

# dmenu
# https://tools.suckless.org/dmenu/

# Dependencies:
# – ripgrep (https://github.com/BurntSushi/ripgrep)

rg --line-number --with-filename '.+' "$@" |
dmenu -l 20 -i -p 'Open files (search by content)' |

while read line; do
  # Output format: <file>:<line>:<text>
  file=${line%%:*}
  line_number=${line#*:}; line_number=${line_number%%:*}

  :edit "$file" "+$line_number"
done
